package ch.psi.pshell.xscan.plot;

import ch.psi.pshell.plot.MatrixPlotSeries;
import ch.psi.pshell.plot.Plot;

public class XYZSeriesDataFilter implements SeriesDataFilter {

	private final String idX;
	private final String idY;
	private final String idZ;
	
	// Name of the series generated by this filter
	private String seriesName = "";
	
	// Number of series generated for this filter 
	private int count = 0;
	
	// Plot the data of this filter goes to
	private final Plot plot;
	
	private boolean newseries = false;
	
	
	public XYZSeriesDataFilter(String idX, String idY, String idZ, Plot plot){
		this.idX = idX;
		this.idY = idY;
		this.idZ = idZ;
		this.plot = plot;
	}

	public String getIdZ() {
		return idZ;
	}
	public String getSeriesName() {
		return seriesName;
	}
	public void setSeriesName(String seriesName) {
		this.seriesName = seriesName;
	}
        
	private MatrixPlotSeries series = null;
        
        @Override
        public MatrixPlotSeries getSeries(){
            return series;
        }        
        public void setSeries(MatrixPlotSeries series){
            this.series=series;
        }              
	public int getCount() {
		return count;
	}
	public void setCount(int count) {
		this.count = count;
	}
	public boolean isNewseries() {
		return newseries;
	}
	public void setNewseries(boolean newseries) {
		this.newseries = newseries;
	}
	public String getIdX() {
		return idX;
	}
	public String getIdY() {
		return idY;
	}
	public Plot getPlot() {
		return plot;
	}
	
}
