package ch.psi.pshell.plotter;

import ch.psi.pshell.core.LogManager;
import ch.psi.pshell.ui.AboutDialog;
import ch.psi.pshell.ui.App;
import ch.psi.utils.State;
import ch.psi.utils.Sys;
import ch.psi.utils.swing.ConfigDialog;
import ch.psi.utils.swing.MainFrame;
import ch.psi.utils.swing.StandardDialog;
import ch.psi.utils.swing.SwingUtils;
import java.awt.Window;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;

/**
 *
 */
public class View extends MainFrame {
    public static final String ARG_SERVER_PORT = "port";
    public static final String ARG_TITLE = "title";
    
    static final Logger logger = Logger.getLogger(View.class.getName());
    final Plotter pm;
    final PlotServer ps;
    final LogManager logManager;

    public View() {
        this(-1);
    }
    
    public View(int port) {
        super();
        initComponents();
        setIcon(getClass().getResource("/ch/psi/pshell/ui/Icon.ico"));

        pm = new DesktopPlotter(plotPane);
        if (port > 0){
            ps = new PlotServer(port, pm);
        } else {
            ps = new PlotServer(pm);
        }
        
        if (App.hasArgument(ARG_TITLE)){
            setTitle(App.getArgumentValue(ARG_TITLE));
        } else {
            setTitle("Plotter [" + ps.getAddress() + "]");
        }

        loggerPanel.setOutputLength(1000);
        //loggerPanel.setInverted(true);
        loggerPanel.start();
        logManager = new LogManager();
        logManager.start(null, 0);
        logManager.setLevel(Level.FINE);
        logManager.setConsoleLoggerLevel(Level.OFF);
        loggerPanel.setVisible(false);

        boolean persist  = (App.isPlotServer() && App.isDetachedPersisted()) || !App.isLocalMode();
        //After ps is instantiated-> the context file depends on the port & host.
        if (persist){
             restoreState();
        } else {
            if (App.getSize()!=null){
                SwingUtilities.invokeLater(()->{
                    View.this.setSize(App.getSize());
                    SwingUtils.centerComponent(null, View.this);                    
                });
            }
        }
        
        logger.info("Listening socket: " + ps.getAddress());
    }

    /**
     * Called when window is being closed
     */
    @Override
    protected void onClosing() {
        saveState();
        try {
            ps.close();
        } catch (Exception ex) {
            logger.log(Level.WARNING, null, ex);
        }
        setVisible(false);
        dispose();
        System.exit(0);
    }

    @Override
    protected void onTimer() {
        if (!ps.isRunning()) {
            statusBar.setApplicationState(State.Fault);
            statusBar.setStatusMessage("Server thread stopped.");
        }
    }

    @Override
    protected void onCreate() {
        statusBar.setApplicationState(State.Ready);
    }

    @Override
    public String getSessionPath() {
        return Sys.getUserHome();
    }

    @Override
    protected String getSessionFilename(Window window) {
        return "." + getComponentName(window) + "." + Sys.getLocalHost() + "_" + ps.port + ".session." + sessionEncoder.toString();
    }

    void updatePanel() {
        try {
            PlotPanel panel = plotPane.getCurrentPanel();
            String status = panel.status;
            Double progress = panel.progress;

            if (progress == null) {
                statusBar.setApplicationState(State.Ready);
            } else {
                statusBar.setApplicationState(State.Busy);
                statusBar.setProgress(progress);
            }
            statusBar.setStatusMessage(status);
        } catch (Exception ex) {
            logger.log(Level.WARNING, null, ex);
        }
    }

    static String getHelpMessage() {
        StringBuilder sb = new StringBuilder();
        sb.append("Arguments:");
        sb.append("\n\t-h\tPrint this help message");
        sb.append("\n\t-l\tLocal mode: No GUI state persistence");
        sb.append("\n\t-size=WxH    \tSet application window size if GUI state not persisted");
        sb.append("\n\t-port=<int>  \tSet the plot server port (default: 7777)");
        sb.append("\n\t-title=<str> \tSet the main window title");
        sb.append("\n");
        return sb.toString();
    }

    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statusBar = new ch.psi.pshell.ui.StatusBar();
        plotPane = new ch.psi.pshell.plotter.PlotPane();
        loggerPanel = new ch.psi.pshell.swing.LoggerPanel();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        javax.swing.JMenuItem menuExit = new javax.swing.JMenuItem();
        menuView = new javax.swing.JMenu();
        menuFullScreen = new javax.swing.JCheckBoxMenuItem();
        menuLogs = new javax.swing.JCheckBoxMenuItem();
        jSeparator13 = new javax.swing.JPopupMenu.Separator();
        menuCloseAllPlots = new javax.swing.JMenuItem();
        jSeparator20 = new javax.swing.JPopupMenu.Separator();
        menuPreferences = new javax.swing.JMenuItem();
        javax.swing.JMenu menuHelp = new javax.swing.JMenu();
        menuSetup = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        javax.swing.JMenuItem menuAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("PlotServer"); // NOI18N

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("ch/psi/pshell/ui/View"); // NOI18N
        menuFile.setText(bundle.getString("View.menuFile.text")); // NOI18N

        menuExit.setText(bundle.getString("View.menuExit.text")); // NOI18N
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        menuFile.add(menuExit);

        menuBar.add(menuFile);

        menuView.setText(bundle.getString("View.menuView.text")); // NOI18N
        menuView.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                menuViewStateChanged(evt);
            }
        });

        menuFullScreen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuFullScreen.setSelected(true);
        menuFullScreen.setText(bundle.getString("View.menuFullScreen.text")); // NOI18N
        menuFullScreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFullScreenActionPerformed(evt);
            }
        });
        menuView.add(menuFullScreen);

        menuLogs.setText(bundle.getString("View.menuViewLogs.text")); // NOI18N
        menuLogs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogsActionPerformed(evt);
            }
        });
        menuView.add(menuLogs);
        menuView.add(jSeparator13);

        menuCloseAllPlots.setText(bundle.getString("View.menuCloseAllPlots.text")); // NOI18N
        menuCloseAllPlots.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCloseAllPlotsActionPerformed(evt);
            }
        });
        menuView.add(menuCloseAllPlots);
        menuView.add(jSeparator20);

        menuPreferences.setText(bundle.getString("View.menuPreferences.text")); // NOI18N
        menuPreferences.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPreferencesActionPerformed(evt);
            }
        });
        menuView.add(menuPreferences);

        menuBar.add(menuView);

        menuHelp.setText(bundle.getString("View.menuHelp.text")); // NOI18N

        menuSetup.setText("Setup");
        menuSetup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSetupActionPerformed(evt);
            }
        });
        menuHelp.add(menuSetup);
        menuHelp.add(jSeparator1);

        menuAbout.setText(bundle.getString("View.menuAbout.text")); // NOI18N
        menuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAboutActionPerformed(evt);
            }
        });
        menuHelp.add(menuAbout);

        menuBar.add(menuHelp);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(loggerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(plotPane, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(plotPane, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(loggerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(statusBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        onClosing();
    }//GEN-LAST:event_menuExitActionPerformed

    private void menuFullScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFullScreenActionPerformed
        try {
            setFullScreen(menuFullScreen.isSelected());
        } catch (Exception ex) {
            showException(ex);
        } catch (Error e) {
            logger.severe(e.toString());
        }
    }//GEN-LAST:event_menuFullScreenActionPerformed

    private void menuCloseAllPlotsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCloseAllPlotsActionPerformed
        try {
            plotPane.clear();
        } catch (Exception ex) {
            showException(ex);
        }
    }//GEN-LAST:event_menuCloseAllPlotsActionPerformed

    private void menuPreferencesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPreferencesActionPerformed
        try {
            ConfigDialog dlg = new ConfigDialog(this, true);
            dlg.setTitle("Preferences");
            dlg.setConfig(plotPane.getPreferences());
            dlg.setSize(600, 480);
            showChildWindow(dlg);
            if (dlg.getResult()) {
                plotPane.getPreferences().save();
                plotPane.applyPreferences();
            }
        } catch (Exception ex) {
            showException(ex);
        }
    }//GEN-LAST:event_menuPreferencesActionPerformed

    private void menuViewStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_menuViewStateChanged
        if (menuView.isSelected()) {
            try {
                menuFullScreen.setSelected(isFullScreen());
            } catch (Exception ex) {
            }
        }
    }//GEN-LAST:event_menuViewStateChanged

    private void menuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAboutActionPerformed
        AboutDialog aboutDialog = new AboutDialog(this, true);
        aboutDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        showChildWindow(aboutDialog);
    }//GEN-LAST:event_menuAboutActionPerformed

    String text;
    String marker;
    private void menuLogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogsActionPerformed
        loggerPanel.setVisible(menuLogs.isSelected());
    }//GEN-LAST:event_menuLogsActionPerformed

    private void menuSetupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSetupActionPerformed
        try {
            String[][] entries = new String[][]{
                {"Process", Sys.getProcessName()},
                {"User", Sys.getUserName()},
                {"Version", App.getApplicationBuildInfo()},
                {"Java", System.getProperty("java.vm.name") + " (" + System.getProperty("java.version") + ")"},
                {"Arguments", String.join(" ", App.getArguments())},
                {"Current folder", new File(".").getCanonicalPath()},
                {"Preferences", PlotPane.preferences.getFileName()},
                {"Socket", ps.getAddress()}};

            JTable table = new JTable();
            table.setModel(new DefaultTableModel(
                    entries,
                    new String[]{
                        "Parameter", "Value"
                    }
            ) {
                public Class
                        getColumnClass(int columnIndex) {
                    return String.class;
                }

                @Override
                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return (columnIndex == 1);
                }
            });
            //table.setPreferredSize(new Dimension(400,200));
            table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
            table.getColumnModel().getColumn(0).setPreferredWidth(150);
            table.getColumnModel().getColumn(1).setPreferredWidth(450);
            JTextField textField = new JTextField();
            textField.setEditable(false);
            DefaultCellEditor editor = new DefaultCellEditor(textField);
            table.getColumnModel().getColumn(1).setCellEditor(editor);
            StandardDialog dlg = new StandardDialog(this, "Setup", true);
            dlg.setContentPane(table);
            dlg.pack();
            dlg.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            //dlg.setResizable(false);
            showChildWindow(dlg);

        } catch (Exception ex) {
            showException(ex);
        }
    }//GEN-LAST:event_menuSetupActionPerformed
    
    public static void create(int port){
        if (App.isDebug()){
            PlotServer.debug = true;
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new View(port).setVisible(true);
            }
        });        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
        App.init(args);
        System.out.println(App.getHeaderMessage());
        System.out.println("Version " + App.getApplicationBuildInfo());
        
        if (App.isVersionMessage()) {
            return;
        }

        if (App.isHelpMessage()) {            
            System.out.println(getHelpMessage());
            return;            
        }
        int port = -1;
        if (App.hasArgument(ARG_SERVER_PORT)){
            port = Integer.valueOf(App.getArgumentValue(ARG_SERVER_PORT));
        }
        
        create(port);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator20;
    private ch.psi.pshell.swing.LoggerPanel loggerPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuCloseAllPlots;
    private javax.swing.JMenu menuFile;
    private javax.swing.JCheckBoxMenuItem menuFullScreen;
    private javax.swing.JCheckBoxMenuItem menuLogs;
    private javax.swing.JMenuItem menuPreferences;
    private javax.swing.JMenuItem menuSetup;
    private javax.swing.JMenu menuView;
    private ch.psi.pshell.plotter.PlotPane plotPane;
    private ch.psi.pshell.ui.StatusBar statusBar;
    // End of variables declaration//GEN-END:variables
}
