package ch.psi.pshell.xscan.ui;

import ch.psi.pshell.xscan.model.Action;
import ch.psi.pshell.xscan.model.ContinuousDimension;
import ch.psi.pshell.xscan.model.ContinuousPositioner;
import ch.psi.pshell.xscan.model.Detector;
import java.awt.Component;

/**
 *
 */
public class ContinuousDimensionPanel extends EditablePanel<ContinuousDimension> {

    final ContinuousDimension dimension;

    public ContinuousDimensionPanel() {
        this(new ContinuousDimension());
    }

    /**
     * Creates new form ContinuousDimensionPanel
     */
    public ContinuousDimensionPanel(final ContinuousDimension dimension) {
        super(dimension);
        this.dimension = dimension;
        if (dimension.getPositioner() == null) {
            dimension.setPositioner(new ContinuousPositioner());
        }

        initComponents();

        setManagedFields(jButton1,
                new Component[]{},
                new Component[]{collapsibleListContainerPreActions, collapsibleListContainer1, collapsibleListContainerPostActions, jCheckBoxDataGroup, jCheckBoxZigZag},
                new String[]{null, null, null, "false", "false"}
        );

        collapsibleListContainerPreActions.setHeader("Pre Actions");
        collapsibleListContainerPreActions.setName("Pre Actions");

        collapsibleListContainerPostActions.setHeader("Post Actions");
        collapsibleListContainerPostActions.setName("Post Actions");

        collapsibleListContainer1.setHeader("Detectors");
        collapsibleListContainer1.setName("Detectors");

        // Establish bindings
        bindEditor(jCheckBoxDataGroup, "dataGroup");
        bindEditor(jCheckBoxZigZag, "zigzag");
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        continuousPositionerPanel1 = new ContinuousPositionerPanel(dimension.getPositioner());
        collapsibleListContainer1 = new CollapsibleListContainer<Detector>(new ContinuousDetectorListItemProvider(dimension));
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        collapsibleListContainerPreActions = new CollapsibleListContainer<Action>(new ActionListItemProvider(dimension.getPreAction()));
        collapsibleListContainerPostActions = new CollapsibleListContainer<Action>(new ActionListItemProvider(dimension.getPostAction()));
        jPanel2 = new javax.swing.JPanel();
        jCheckBoxDataGroup = new javax.swing.JCheckBox();
        jCheckBoxZigZag = new javax.swing.JCheckBox();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        setPreferredSize(new java.awt.Dimension(500, 100));

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ch/psi/pshell/xscan/ui/icons/plus.png"))); // NOI18N
        jButton1.setToolTipText("Add optional items");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jPanel1.add(jButton1);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jCheckBoxDataGroup.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jCheckBoxDataGroup.setText("Data Group");
        jCheckBoxDataGroup.setName("Data Group"); // NOI18N
        jPanel2.add(jCheckBoxDataGroup);

        jCheckBoxZigZag.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jCheckBoxZigZag.setText("ZigZag");
        jCheckBoxZigZag.setToolTipText("ZigZag");
        jCheckBoxZigZag.setName("ZigZag"); // NOI18N
        jPanel2.add(jCheckBoxZigZag);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
            .addComponent(collapsibleListContainerPreActions, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
            .addComponent(continuousPositionerPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, Short.MAX_VALUE)
            .addComponent(collapsibleListContainer1, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
            .addComponent(collapsibleListContainerPostActions, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(collapsibleListContainerPreActions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(continuousPositionerPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(collapsibleListContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(collapsibleListContainerPostActions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ch.psi.pshell.xscan.ui.CollapsibleListContainer collapsibleListContainer1;
    private ch.psi.pshell.xscan.ui.CollapsibleListContainer collapsibleListContainerPostActions;
    private ch.psi.pshell.xscan.ui.CollapsibleListContainer collapsibleListContainerPreActions;
    private ch.psi.pshell.xscan.ui.ContinuousPositionerPanel continuousPositionerPanel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBoxDataGroup;
    private javax.swing.JCheckBox jCheckBoxZigZag;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

}
