package ch.psi.pshell.xscan.ui;

import ch.psi.pshell.xscan.model.DiscreteStepPositioner;
import java.awt.Component;
import javax.swing.JFormattedTextField;

/**
 *
 */
public class DiscreteStepPositionerPanel extends EditablePanel<DiscreteStepPositioner> {

    private WrapLayout manager;

    public DiscreteStepPositionerPanel() {
        this(new DiscreteStepPositioner() {
        });
    }

    /**
     * Creates new form DiscreteStepPositionerPanel
     */
    public DiscreteStepPositionerPanel(final DiscreteStepPositioner positioner) {
        super(positioner);
        if (positioner.getId() == null || positioner.getId().equals("")) {
            positioner.setId(IdGenerator.generateId());
        }

        initComponents();

        setManagedFields(jButton1,
                new Component[]{jTextFieldName},
                new Component[]{jTextFieldReadback, jFormattedTextFieldSettlingTime, jTextFieldDone, jFormattedTextFieldDoneValue, jFormattedTextFieldDoneDelay, jCheckBoxAsynchronous, jComboBoxType},
                new String[]{null, "0.0", null, "1", "0.0", "false", "Integer"}
        );

        // Establish bindings
        bindIdEditor(jTextFieldId);
        bindEditor(jTextFieldName, "name", true);
        bindEditor(jTextFieldReadback, "readback", true);
        bindEditor(jFormattedTextFieldSettlingTime, "settlingTime", true, null);
        bindEditor(jTextFieldDone, "done", true);
        bindEditor(jTextFieldName, "name", true);
        bindEditor(jFormattedTextFieldDoneValue, "doneValue", true, null);
        bindEditor(jFormattedTextFieldDoneDelay, "doneDelay", true, null);
        bindEditor(jCheckBoxAsynchronous, "asynchronous");
        bindEditor(jComboBoxType, "type");

        manager = new WrapLayout(WrapLayout.LEADING);
        manager.setVgap(0);
        this.jPanel1.setLayout(manager);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jTextFieldName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldReadback = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextFieldSettlingTime = new JFormattedTextField(FieldUtilities.getDecimalFormat());
        jLabel4 = new javax.swing.JLabel();
        jTextFieldDone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jFormattedTextFieldDoneValue = new JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxType = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jFormattedTextFieldDoneDelay = new JFormattedTextField(FieldUtilities.getDecimalFormat());
        jCheckBoxAsynchronous = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setLabelFor(jTextFieldId);
        jLabel1.setText("Id:");
        jPanel1.add(jLabel1);

        jTextFieldId.setBackground(getBackground());
        jTextFieldId.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jTextFieldId.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldId.setText("Id");
        jTextFieldId.setBorder(null);
        jTextFieldId.setInputVerifier(new IdInputVerifier());
        jTextFieldId.setPreferredSize(new java.awt.Dimension(80, 16));
        jPanel1.add(jTextFieldId);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("ch/psi/pshell/xscan/ui/Bundle"); // NOI18N
        jTextFieldName.setText(bundle.getString("DiscreteStepPositionerPanel.jTextFieldName.text")); // NOI18N
        jTextFieldName.setToolTipText(bundle.getString("DiscreteStepPositionerPanel.jTextFieldName.toolTipText")); // NOI18N
        jTextFieldName.setName("Name"); // NOI18N
        jTextFieldName.setPreferredSize(new java.awt.Dimension(180, 28));
        jPanel1.add(jTextFieldName);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setLabelFor(jTextFieldReadback);
        jLabel2.setText(bundle.getString("DiscreteStepPositionerPanel.jLabel2.text")); // NOI18N
        jPanel1.add(jLabel2);

        jTextFieldReadback.setToolTipText("Readback channel of the positioner");
        jTextFieldReadback.setName("Readback"); // NOI18N
        jTextFieldReadback.setPreferredSize(new java.awt.Dimension(180, 28));
        jPanel1.add(jTextFieldReadback);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setLabelFor(jFormattedTextFieldSettlingTime);
        jLabel3.setText(bundle.getString("DiscreteStepPositionerPanel.jLabel3.text")); // NOI18N
        jPanel1.add(jLabel3);

        jFormattedTextFieldSettlingTime.setToolTipText("Positioner settling time");
        jFormattedTextFieldSettlingTime.setName("Settling Time"); // NOI18N
        jFormattedTextFieldSettlingTime.setPreferredSize(new java.awt.Dimension(40, 28));
        jPanel1.add(jFormattedTextFieldSettlingTime);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setLabelFor(jTextFieldDone);
        jLabel4.setText(bundle.getString("DiscreteStepPositionerPanel.jLabel4.text")); // NOI18N
        jPanel1.add(jLabel4);

        jTextFieldDone.setToolTipText("Value of done channel that indicated done (Integer)");
        jTextFieldDone.setName("Done"); // NOI18N
        jTextFieldDone.setPreferredSize(new java.awt.Dimension(180, 28));
        jPanel1.add(jTextFieldDone);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel5.setLabelFor(jFormattedTextFieldDoneValue);
        jLabel5.setText(bundle.getString("DiscreteStepPositionerPanel.jLabel5.text")); // NOI18N
        jPanel1.add(jLabel5);

        jFormattedTextFieldDoneValue.setToolTipText("Value of done channel that indicated done (Integer)");
        jFormattedTextFieldDoneValue.setName("Done Value"); // NOI18N
        jFormattedTextFieldDoneValue.setPreferredSize(new java.awt.Dimension(40, 28));
        jPanel1.add(jFormattedTextFieldDoneValue);

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel7.setLabelFor(jComboBoxType);
        jPanel1.add(jLabel7);

        jComboBoxType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Integer", "String", "Double" }));
        jComboBoxType.setName("Done Value Type"); // NOI18N
        jPanel1.add(jComboBoxType);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel6.setLabelFor(jFormattedTextFieldDoneDelay);
        jLabel6.setText(bundle.getString("DiscreteStepPositionerPanel.jLabel6.text")); // NOI18N
        jPanel1.add(jLabel6);

        jFormattedTextFieldDoneDelay.setToolTipText("Delay before done channel is checked");
        jFormattedTextFieldDoneDelay.setName("Done Delay"); // NOI18N
        jFormattedTextFieldDoneDelay.setPreferredSize(new java.awt.Dimension(60, 28));
        jPanel1.add(jFormattedTextFieldDoneDelay);

        jCheckBoxAsynchronous.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jCheckBoxAsynchronous.setText("Asynchronous:");
        jCheckBoxAsynchronous.setToolTipText("Asynchronous");
        jCheckBoxAsynchronous.setName("Asynchronous"); // NOI18N
        jPanel1.add(jCheckBoxAsynchronous);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ch/psi/pshell/xscan/ui/icons/plus.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jPanel1.add(jButton1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 851, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBoxAsynchronous;
    private javax.swing.JComboBox jComboBoxType;
    private javax.swing.JFormattedTextField jFormattedTextFieldDoneDelay;
    private javax.swing.JFormattedTextField jFormattedTextFieldDoneValue;
    private javax.swing.JFormattedTextField jFormattedTextFieldSettlingTime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldDone;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldReadback;
    // End of variables declaration//GEN-END:variables

}
