//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.27 at 11:18:50 AM CEST 
//


package ch.psi.pshell.xscan.model;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Dimension complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Dimension">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="zigzag" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="dataGroup" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Dimension")
@XmlSeeAlso({
    ContinuousDimension.class,
    DiscreteStepDimension.class
})
public abstract class Dimension
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlAttribute(name = "zigzag")
    protected Boolean zigzag;
    @XmlAttribute(name = "dataGroup")
    protected Boolean dataGroup;

    /**
     * Gets the value of the zigzag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isZigzag() {
        if (zigzag == null) {
            return false;
        } else {
            return zigzag;
        }
    }

    /**
     * Sets the value of the zigzag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setZigzag(Boolean value) {
        this.zigzag = value;
    }

    /**
     * Gets the value of the dataGroup property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isDataGroup() {
        if (dataGroup == null) {
            return false;
        } else {
            return dataGroup;
        }
    }

    /**
     * Sets the value of the dataGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDataGroup(Boolean value) {
        this.dataGroup = value;
    }

}
