//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.27 at 11:18:50 AM CEST 
//


package ch.psi.pshell.xscan.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DiscreteStepDimension complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DiscreteStepDimension">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.psi.ch/~ebner/models/scan/1.0}Dimension">
 *       &lt;sequence>
 *         &lt;element name="preAction" type="{http://www.psi.ch/~ebner/models/scan/1.0}Action" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="positioner" type="{http://www.psi.ch/~ebner/models/scan/1.0}DiscreteStepPositioner" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="action" type="{http://www.psi.ch/~ebner/models/scan/1.0}Action" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="guard" type="{http://www.psi.ch/~ebner/models/scan/1.0}Guard" minOccurs="0"/>
 *         &lt;element name="detector" type="{http://www.psi.ch/~ebner/models/scan/1.0}Detector" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="postAction" type="{http://www.psi.ch/~ebner/models/scan/1.0}Action" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DiscreteStepDimension", propOrder = {
    "preAction",
    "positioner",
    "action",
    "guard",
    "detector",
    "postAction"
})
public class DiscreteStepDimension
    extends Dimension
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected List<Action> preAction;
    protected List<DiscreteStepPositioner> positioner;
    protected List<Action> action;
    protected Guard guard;
    protected List<Detector> detector;
    protected List<Action> postAction;

    /**
     * Gets the value of the preAction property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the preAction property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPreAction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Action }
     * 
     * 
     */
    public List<Action> getPreAction() {
        if (preAction == null) {
            preAction = new ArrayList<Action>();
        }
        return this.preAction;
    }

    /**
     * Gets the value of the positioner property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the positioner property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPositioner().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DiscreteStepPositioner }
     * 
     * 
     */
    public List<DiscreteStepPositioner> getPositioner() {
        if (positioner == null) {
            positioner = new ArrayList<DiscreteStepPositioner>();
        }
        return this.positioner;
    }

    /**
     * Gets the value of the action property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the action property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Action }
     * 
     * 
     */
    public List<Action> getAction() {
        if (action == null) {
            action = new ArrayList<Action>();
        }
        return this.action;
    }

    /**
     * Gets the value of the guard property.
     * 
     * @return
     *     possible object is
     *     {@link Guard }
     *     
     */
    public Guard getGuard() {
        return guard;
    }

    /**
     * Sets the value of the guard property.
     * 
     * @param value
     *     allowed object is
     *     {@link Guard }
     *     
     */
    public void setGuard(Guard value) {
        this.guard = value;
    }

    /**
     * Gets the value of the detector property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the detector property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDetector().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Detector }
     * 
     * 
     */
    public List<Detector> getDetector() {
        if (detector == null) {
            detector = new ArrayList<Detector>();
        }
        return this.detector;
    }

    /**
     * Gets the value of the postAction property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the postAction property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPostAction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Action }
     * 
     * 
     */
    public List<Action> getPostAction() {
        if (postAction == null) {
            postAction = new ArrayList<Action>();
        }
        return this.postAction;
    }

}
