package ch.psi.pshell.swing;

import ch.psi.pshell.device.Device;
import ch.psi.utils.State;

/**
 *
 */
public final class DeviceStatePanel extends DevicePanel {

    public DeviceStatePanel() {
        initComponents();
    }

    @Override
    protected void onDeviceStateChanged(State state, State former) {
        labelState.setText(String.valueOf(state));
    }

    @Override
    public void setDevice(Device device) {
        super.setDevice(device);
        if (device == null) {
            labelState.setText(" ");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelState = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("State"));

        labelState.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelState, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelState, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelState;
    // End of variables declaration//GEN-END:variables
}
