package ch.psi.pshell.swing;

import ch.psi.pshell.core.Context;
import ch.psi.pshell.core.ContextAdapter;
import ch.psi.utils.State;
import ch.psi.utils.swing.MonitoredPanel;
import ch.psi.utils.swing.SwingUtils;
import java.awt.Component;
import java.util.HashMap;
import javax.swing.JButton;
import javax.swing.JSpinner;
import javax.swing.text.JTextComponent;
import ch.psi.pshell.core.ContextListener;

/**
 *
 */
public class ScriptButton extends MonitoredPanel {


    public ScriptButton() {
        initComponents();
    }

    ContextListener contextListener;

    @Override
    protected void onShow() {
        contextListener = new ContextAdapter() {
            @Override
            public void onContextStateChanged(State state, State former) {
                button.setEnabled(state.isReady());
            }
        };
        Context.getInstance().addListener(contextListener);
        button.setEnabled(Context.getInstance().getState().isReady());
    }

    @Override
    protected void onHide() {
        Context.getInstance().removeListener(contextListener);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button = new javax.swing.JButton();

        button.setText("Start");
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(button, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(button)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
        try {
            HashMap<String, Object> args = new HashMap<>();
            if (arguments != null) {
                for (String arg : arguments) {
                    Object val = null;
                    try {
                        Component c = SwingUtils.getComponentByName(getTopLevelAncestor(), arg);
                        if (c instanceof JSpinner) {
                            val = ((JSpinner) c).getValue();
                        } else if (c instanceof JTextComponent) {
                            val = ((JTextComponent) c).getText();
                        } else if (c instanceof JButton) {
                            val = ((JButton) c).isSelected();
                        }
                    } catch (Exception ex) {
                    }
                    args.put(arg, val);
                }
            }
            Context.getInstance().evalFileAsync(script, args);
        } catch (Context.ContextStateException ex) {
            showException(ex);
        }
    }//GEN-LAST:event_buttonActionPerformed

    String script = "Script";

    public String getScript() {
        return script;
    }

    public void setScript(String script) {
        this.script = script;
    }

    public String getText() {
        return button.getText();
    }

    public void setText(String text) {
        button.setText(text);
    }

    String[] arguments;

    public String[] getArguments() {
        return arguments;
    }

    public void setArguments(String[] arguments) {
        this.arguments = arguments;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button;
    // End of variables declaration//GEN-END:variables
}
