#!/bin/sh

JAVA_HOME="/usr/lib/jvm/java-${app_jdk}-openjdk"

# If JAVA_HOME is found, use its java binary; otherwise, fall back to system java
if [ -x "\$JAVA_HOME/bin/java" ]; then
    JAVA_CMD="\$JAVA_HOME/bin/java"
else
    JAVA_CMD="java"
fi

# Read JVM options from environment variables PSHELL_JVM_OPTIONS and APP_NAME_JVM_OPTIONS
APP_JVM_OPTIONS_NAME=\$(echo "APP_${app_name}" | tr '[:lower:]' '[:upper:]')_JVM_OPTIONS
APP_ARGS_NAME=\$(echo "APP_${app_name}" | tr '[:lower:]' '[:upper:]')_ARGS

# Run the JAR with all passed arguments
exec "\$JAVA_CMD" "\$PSHELL_JVM_OPTIONS" \${!APP_JVM_OPTIONS_NAME} -jar ${jar_file} \${!APP_ARGS_NAME} "\$@"
