package ch.psi.pshell.csm;

import ch.psi.pshell.app.Setup;
import java.util.Optional;
import java.util.logging.Logger;

/**
 *
 */
public class View extends ch.psi.pshell.app.MainFrame {

    /**
     * Creates new form MainFrame
     */
    public View() {
        initComponents();
        setTitle(Optional.ofNullable(Setup.getTitle()).orElse("CamServer Management Console"));
        loggerPanel.start();
        panelCameras.getPanelConfig().disableFixedCameras();           
    }
    
    public static View getInstance(){
        return (View) ch.psi.pshell.app.MainFrame.getInstance();
    }
        
    /**
     * Called once when frame is created, before being visible
     */
    @Override
    protected void onCreate() {
        Logger.getLogger(View.class.getName()).info("Startup");
        panelCameras.setUrl(App.getCameraServer());
        panelPipelines.setUrl(App.getPipelineServer());       
        panelDataBuffer.setUrl(App.getPipelineServer());          
        panelUserScripts.setUrl(App.getPipelineServer());       
        backgroundPanel.setUrl(App.getPipelineServer(), App.getCameraServer());
        
        if (App.getDataBufferSourcesRepo().isBlank()  && App.getImageBufferSourcesRepo().isBlank()){
            tabPane.removeTabAt(tabPane.indexOfTab("DataBuffer"));
        } else if (App.getDataBufferSourcesRepo().isBlank()){
            dataBufferPane.removeTabAt(0);
        } else if (App.getImageBufferSourcesRepo().isBlank()){
            dataBufferPane.removeTabAt(1);
        }
    }
    
    /**
     * Called once in the first time the frame is shown
     */
    @Override
    protected void onOpen() {
    }

    /**
     * Called once when the frame is about to be disposed
     */
    @Override
    protected void onDispose() {
    }

    /**
     * Called every time the frame is shown (also before open is called)
     */
    @Override
    protected void onShow() {
    }

    /**
     * Called every time the frame is hidden (also before disposed)
     */
    protected void onHide() {
    }

    /**
     * Called every second if the frame is visible
     */
    @Override
    protected void onTimer() {        
    }

    /**
     * Called when window is being closed
     */
    @Override
    protected void onClosing() {
    }
    
    
    public int getSelectedTabIndex() {
        return tabPane.getSelectedIndex();
    }
    
    public String getSelectedTabTitle(){
        return tabPane.getTitleAt(getSelectedTabIndex());
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jToolBar2 = new javax.swing.JToolBar();
        tabPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        panelPipelines = new ch.psi.pshell.csm.PanelServer();
        jPanel2 = new javax.swing.JPanel();
        panelCameras = new ch.psi.pshell.csm.PanelServer();
        backgroundPanel = new ch.psi.pshell.csm.BackgroundPanel();
        panelUserScripts = new ch.psi.pshell.csm.PanelUserScripts();
        dataBufferPane = new javax.swing.JTabbedPane();
        panelDataBuffer = new ch.psi.pshell.csm.DataBufferPanel();
        panelImageBuffer = new ch.psi.pshell.csm.ImageBufferConfigPanel();
        jPanel4 = new javax.swing.JPanel();
        loggerPanel = new ch.psi.pshell.swing.LoggerPanel();

        jToolBar1.setRollover(true);

        jToolBar2.setRollover(true);

        panelPipelines.setPipeline(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPipelines, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPipelines, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
        );

        tabPane.addTab("Pipelines", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCameras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCameras, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
        );

        tabPane.addTab("Cameras", jPanel2);
        tabPane.addTab("Background", backgroundPanel);
        tabPane.addTab("User Scripts", panelUserScripts);

        dataBufferPane.addTab("Reconnection", panelDataBuffer);
        dataBufferPane.addTab("ImageBuffer Config", panelImageBuffer);

        tabPane.addTab("DataBuffer", dataBufferPane);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loggerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loggerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabPane.addTab("Logs", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPane, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPane, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ch.psi.pshell.csm.BackgroundPanel backgroundPanel;
    private javax.swing.JTabbedPane dataBufferPane;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private ch.psi.pshell.swing.LoggerPanel loggerPanel;
    private ch.psi.pshell.csm.PanelServer panelCameras;
    private ch.psi.pshell.csm.DataBufferPanel panelDataBuffer;
    private ch.psi.pshell.csm.ImageBufferConfigPanel panelImageBuffer;
    private ch.psi.pshell.csm.PanelServer panelPipelines;
    private ch.psi.pshell.csm.PanelUserScripts panelUserScripts;
    private javax.swing.JTabbedPane tabPane;
    // End of variables declaration//GEN-END:variables
}
