//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.27 at 11:18:50 AM CEST 
//


package ch.psi.pshell.xscan.model;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * <p>Java class for ShellAction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ShellAction">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.psi.ch/~ebner/models/scan/1.0}Action">
 *       &lt;attribute name="command" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="exitValue" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *       &lt;attribute name="checkExitValue" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ShellAction")
public class ShellAction
    extends Action
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlAttribute(name = "command", required = true)
    protected String command;
    @XmlAttribute(name = "exitValue")
    protected Integer exitValue;
    @XmlAttribute(name = "checkExitValue")
    protected Boolean checkExitValue;

    /**
     * Gets the value of the command property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommand() {
        return command;
    }

    /**
     * Sets the value of the command property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommand(String value) {
        this.command = value;
    }

    /**
     * Gets the value of the exitValue property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getExitValue() {
        if (exitValue == null) {
            return  0;
        } else {
            return exitValue;
        }
    }

    /**
     * Sets the value of the exitValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setExitValue(Integer value) {
        this.exitValue = value;
    }

    /**
     * Gets the value of the checkExitValue property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isCheckExitValue() {
        if (checkExitValue == null) {
            return true;
        } else {
            return checkExitValue;
        }
    }

    /**
     * Sets the value of the checkExitValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCheckExitValue(Boolean value) {
        this.checkExitValue = value;
    }

}
