package:
    name: pplot
    version: 1.0.1

build:
  number: 0

source:
    path: ..

requirements:
    build:
        - python
    run:
        - python
        - pyzmq

about:
    summary: "pplot is Python a client to PShell plot server"
