package ch.psi.pshell.xscan.ui;

import ch.psi.pshell.xscan.model.ContinuousPositioner;
import java.awt.Component;
import javax.swing.JFormattedTextField;

/**
 *
 */
public class ContinuousPositionerPanel extends EditablePanel<ContinuousPositioner> {

    private WrapLayout manager;

    public ContinuousPositionerPanel() {
        this(new ContinuousPositioner());
    }

    /** Creates new form ContinuousPositionerPanel */
    public ContinuousPositionerPanel(final ContinuousPositioner positioner) {
        super(positioner);
        if (positioner.getId() == null || positioner.getId().equals("")) {
            positioner.setId(IdGenerator.generateId());
        }
        initComponents();
   
        
        setManagedFields(jButton1, 
            new Component[]{jTextFieldName, jFormattedTextFieldStart, jFormattedTextFieldEnd, jFormattedTextFieldStepSize, jFormattedTextFieldIntegrationTime},
            new Component[]{jTextFieldReadback, jFormattedTextFieldBacklash}
        );        

        // Establish bindings
        bindIdEditor(jTextFieldId);
        bindEditor(jTextFieldName, "name", true);
        bindEditor(jTextFieldReadback, "readback", true);
        bindEditor(jFormattedTextFieldStart, "start", true, 0);
        bindEditor(jFormattedTextFieldEnd, "end", true, 0);
        bindEditor(jFormattedTextFieldStepSize, "stepSize", true, 0);
        bindEditor(jFormattedTextFieldIntegrationTime, "stepSize", true, 0);
        bindEditor(jFormattedTextFieldBacklash, "additionalBacklash", true, null);


        manager = new WrapLayout(WrapLayout.LEADING);
        jPanel1.setLayout(manager);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jTextFieldName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldReadback = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextFieldStart = new JFormattedTextField(FieldUtilities.getDecimalFormat());
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextFieldEnd = new JFormattedTextField(FieldUtilities.getDecimalFormat());
        jLabel5 = new javax.swing.JLabel();
        jFormattedTextFieldStepSize = new JFormattedTextField(FieldUtilities.getDecimalFormat());
        jLabel6 = new javax.swing.JLabel();
        jFormattedTextFieldIntegrationTime = new JFormattedTextField(FieldUtilities.getDecimalFormat());
        jLabel7 = new javax.swing.JLabel();
        jFormattedTextFieldBacklash = new JFormattedTextField(FieldUtilities.getDecimalFormat());
        jButton1 = new javax.swing.JButton();

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setLabelFor(jTextFieldId);
        jLabel1.setText("Id:");
        jPanel1.add(jLabel1);

        jTextFieldId.setBackground(getBackground());
        jTextFieldId.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jTextFieldId.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldId.setText("Id");
        jTextFieldId.setBorder(null);
        jTextFieldId.setInputVerifier(new IdInputVerifier());
        jTextFieldId.setPreferredSize(new java.awt.Dimension(80, 16));
        jPanel1.add(jTextFieldId);

        jTextFieldName.setText("Channel Name");
        jTextFieldName.setToolTipText("Channel Name");
        jTextFieldName.setName("Name"); // NOI18N
        jTextFieldName.setPreferredSize(new java.awt.Dimension(180, 28));
        jPanel1.add(jTextFieldName);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setLabelFor(jTextFieldReadback);
        jLabel2.setText("Readback:");
        jPanel1.add(jLabel2);

        jTextFieldReadback.setToolTipText("Readback");
        jTextFieldReadback.setName("Readback"); // NOI18N
        jTextFieldReadback.setPreferredSize(new java.awt.Dimension(180, 28));
        jPanel1.add(jTextFieldReadback);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setLabelFor(jFormattedTextFieldStart);
        jLabel3.setText("Start:");
        jPanel1.add(jLabel3);

        jFormattedTextFieldStart.setToolTipText("Start");
        jFormattedTextFieldStart.setName("Start"); // NOI18N
        jFormattedTextFieldStart.setPreferredSize(new java.awt.Dimension(80, 28));
        jPanel1.add(jFormattedTextFieldStart);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setLabelFor(jFormattedTextFieldEnd);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("ch/psi/pshell/xscan/ui/Bundle"); // NOI18N
        jLabel4.setText(bundle.getString("ContinuousPositionerPanel.jLabel4.text")); // NOI18N
        jPanel1.add(jLabel4);

        jFormattedTextFieldEnd.setToolTipText("End");
        jFormattedTextFieldEnd.setName("End"); // NOI18N
        jFormattedTextFieldEnd.setPreferredSize(new java.awt.Dimension(80, 28));
        jPanel1.add(jFormattedTextFieldEnd);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel5.setLabelFor(jFormattedTextFieldStepSize);
        jLabel5.setText("Step Size:");
        jPanel1.add(jLabel5);

        jFormattedTextFieldStepSize.setToolTipText("Step Size");
        jFormattedTextFieldStepSize.setName("Step Size"); // NOI18N
        jFormattedTextFieldStepSize.setPreferredSize(new java.awt.Dimension(80, 28));
        jPanel1.add(jFormattedTextFieldStepSize);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel6.setLabelFor(jFormattedTextFieldIntegrationTime);
        jLabel6.setText("Integration Time:");
        jPanel1.add(jLabel6);

        jFormattedTextFieldIntegrationTime.setToolTipText("Integration Time");
        jFormattedTextFieldIntegrationTime.setName("Integration Time"); // NOI18N
        jFormattedTextFieldIntegrationTime.setPreferredSize(new java.awt.Dimension(80, 28));
        jPanel1.add(jFormattedTextFieldIntegrationTime);

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel7.setLabelFor(jFormattedTextFieldBacklash);
        jLabel7.setText("Additional Backlash:");
        jPanel1.add(jLabel7);

        jFormattedTextFieldBacklash.setText(bundle.getString("ContinuousPositionerPanel.jFormattedTextFieldBacklash.text")); // NOI18N
        jFormattedTextFieldBacklash.setToolTipText("Additional backlash");
        jFormattedTextFieldBacklash.setName("Additional backlash"); // NOI18N
        jFormattedTextFieldBacklash.setPreferredSize(new java.awt.Dimension(80, 28));
        jPanel1.add(jFormattedTextFieldBacklash);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ch/psi/pshell/xscan/ui/icons/plus.png"))); // NOI18N
        jButton1.setToolTipText("Add optional item");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jPanel1.add(jButton1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 735, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JFormattedTextField jFormattedTextFieldBacklash;
    private javax.swing.JFormattedTextField jFormattedTextFieldEnd;
    private javax.swing.JFormattedTextField jFormattedTextFieldIntegrationTime;
    private javax.swing.JFormattedTextField jFormattedTextFieldStart;
    private javax.swing.JFormattedTextField jFormattedTextFieldStepSize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldReadback;
    // End of variables declaration//GEN-END:variables

}
