package ch.psi.pshell.xscan.ui;

import ch.psi.pshell.xscan.model.Action;
import ch.psi.pshell.xscan.model.Detector;
import ch.psi.pshell.xscan.model.DiscreteStepDimension;
import ch.psi.pshell.xscan.model.DiscreteStepPositioner;
import ch.psi.pshell.xscan.model.GuardCondition;
import java.awt.Component;

/**
 *
 */
public class DiscreteStepDimensionPanel extends EditablePanel<DiscreteStepDimension> {

    final DiscreteStepDimension dimension;

    public DiscreteStepDimensionPanel() {
        this(new DiscreteStepDimension());
    }

    /**
     * Creates new form DiscreteStepDimensionPanel
     */
    public DiscreteStepDimensionPanel(final DiscreteStepDimension dimension) {
        super(dimension);
        this.dimension = dimension;
        initComponents();

        setManagedFields(jButton1,
                new Component[]{collapsibleListContainerPositioner},
                new Component[]{collapsibleListContainerPreAction, collapsibleListContainerAction, collapsibleListContainerGuard, collapsibleListContainerDetector, collapsibleListContainerPostAction, jCheckBoxDataGroup, jCheckBoxZigZag},
                new String[]{null, null, null, null, null, "false", "false"}
        );

        collapsibleListContainerPositioner.setHeader("Positioners");
        collapsibleListContainerPositioner.setName("Positioners");
        collapsibleListContainerPositioner.setIcon("cog");

        collapsibleListContainerGuard.setHeader("Guards");
        collapsibleListContainerGuard.setName("Guards");

        collapsibleListContainerDetector.setHeader("Detectors");
        collapsibleListContainerDetector.setName("Detectors");
        collapsibleListContainerDetector.setIcon("photo");

        collapsibleListContainerPreAction.setHeader("Pre Actions");
        collapsibleListContainerPreAction.setName("Pre Actions");

        collapsibleListContainerPostAction.setHeader("Post Actions");
        collapsibleListContainerPostAction.setName("Post Actions");

        collapsibleListContainerAction.setHeader("Actions");
        collapsibleListContainerAction.setName("Actions");

        // Establish bindings
        bindEditor(jCheckBoxZigZag, "zigzag");
        bindEditor(jCheckBoxZigZag, "dataGroup");
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        collapsibleListContainerPositioner = new CollapsibleListContainer<DiscreteStepPositioner>(new DiscreteStepPositionerListItemProvider(dimension.getPositioner()));
        collapsibleListContainerDetector = new CollapsibleListContainer<Detector>(new DiscreteStepDetectorListItemProvider(dimension.getDetector()));
        collapsibleListContainerGuard = new CollapsibleListContainer<GuardCondition>(new GuardListItemProvider(dimension));
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jCheckBoxDataGroup = new javax.swing.JCheckBox();
        jCheckBoxZigZag = new javax.swing.JCheckBox();
        collapsibleListContainerPreAction = new CollapsibleListContainer<Action>(new ActionListItemProvider(dimension.getPreAction()));
        collapsibleListContainerPostAction = new CollapsibleListContainer<Action>(new ActionListItemProvider(dimension.getPostAction()));
        collapsibleListContainerAction = new CollapsibleListContainer<Action>(new ActionListItemProvider(dimension.getAction()));

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));

        collapsibleListContainerPositioner.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));

        collapsibleListContainerDetector.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 1, true));

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ch/psi/pshell/xscan/ui/icons/plus.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jPanel1.add(jButton1);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jCheckBoxDataGroup.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jCheckBoxDataGroup.setText("Data Group");
        jCheckBoxDataGroup.setName("Data Group"); // NOI18N
        jPanel2.add(jCheckBoxDataGroup);

        jCheckBoxZigZag.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jCheckBoxZigZag.setText("ZigZag");
        jCheckBoxZigZag.setToolTipText("ZigZag Dimension");
        jCheckBoxZigZag.setName("ZigZag"); // NOI18N
        jPanel2.add(jCheckBoxZigZag);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
            .addComponent(collapsibleListContainerPreAction, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
            .addComponent(collapsibleListContainerPositioner, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
            .addComponent(collapsibleListContainerAction, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
            .addComponent(collapsibleListContainerGuard, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
            .addComponent(collapsibleListContainerDetector, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
            .addComponent(collapsibleListContainerPostAction, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(collapsibleListContainerPreAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(collapsibleListContainerPositioner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(collapsibleListContainerAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(collapsibleListContainerGuard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(collapsibleListContainerDetector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(collapsibleListContainerPostAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ch.psi.pshell.xscan.ui.CollapsibleListContainer collapsibleListContainerAction;
    private ch.psi.pshell.xscan.ui.CollapsibleListContainer collapsibleListContainerDetector;
    private ch.psi.pshell.xscan.ui.CollapsibleListContainer collapsibleListContainerGuard;
    private ch.psi.pshell.xscan.ui.CollapsibleListContainer collapsibleListContainerPositioner;
    private ch.psi.pshell.xscan.ui.CollapsibleListContainer collapsibleListContainerPostAction;
    private ch.psi.pshell.xscan.ui.CollapsibleListContainer collapsibleListContainerPreAction;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBoxDataGroup;
    private javax.swing.JCheckBox jCheckBoxZigZag;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

}
