package ch.psi.pshell.xscan.ui;

import ch.psi.pshell.xscan.model.LinearPositioner;
import javax.swing.JFormattedTextField;

/**
 *
 */
public class LinearPositionerPanel extends EditablePanel<LinearPositioner> {
    final LinearPositioner positioner;
    public LinearPositionerPanel() {
        this(new LinearPositioner());
    }

    /** Creates new form LinearPositionerPanel */
    public LinearPositionerPanel(final LinearPositioner positioner) {
        super(positioner);
        this.positioner=positioner;
        if(positioner.getId() == null || positioner.getId().equals("")){
            positioner.setId(IdGenerator.generateId());
        }
        initComponents();

        // Establish bindings
        bindEditor(jFormattedTextFieldStart, positioner, "start");
        bindEditor(jFormattedTextFieldEnd, positioner, "end");
        bindEditor(jFormattedTextFieldStepSize, positioner, "stepSize");

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        discreteStepPositionerPanel1 = new DiscreteStepPositionerPanel(positioner);
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jFormattedTextFieldStart = new JFormattedTextField(FieldUtilities.getDecimalFormat());
        jLabel2 = new javax.swing.JLabel();
        jFormattedTextFieldEnd = new JFormattedTextField(FieldUtilities.getDecimalFormat());
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextFieldStepSize = new JFormattedTextField(FieldUtilities.getDecimalFormat());

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel1.setLabelFor(jFormattedTextFieldStart);
        jLabel1.setText("Start:"); 
        jPanel1.add(jLabel1);

        jFormattedTextFieldStart.setToolTipText("Start");
        jFormattedTextFieldStart.setName("Start"); // NOI18N
        jFormattedTextFieldStart.setPreferredSize(new java.awt.Dimension(60, 28));
        jPanel1.add(jFormattedTextFieldStart);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel2.setLabelFor(jFormattedTextFieldEnd);
        jLabel2.setText("End:");
        jPanel1.add(jLabel2);

        jFormattedTextFieldEnd.setToolTipText("End");
        jFormattedTextFieldEnd.setName("End"); // NOI18N
        jFormattedTextFieldEnd.setPreferredSize(new java.awt.Dimension(60, 28));
        jPanel1.add(jFormattedTextFieldEnd);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setLabelFor(jFormattedTextFieldStepSize);
        jLabel3.setText("Step Size:");
        jPanel1.add(jLabel3);

        jFormattedTextFieldStepSize.setToolTipText("Step Size");
        jFormattedTextFieldStepSize.setName("StepSize"); // NOI18N
        jFormattedTextFieldStepSize.setPreferredSize(new java.awt.Dimension(60, 28));
        jPanel1.add(jFormattedTextFieldStepSize);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(discreteStepPositionerPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(discreteStepPositionerPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ch.psi.pshell.xscan.ui.DiscreteStepPositionerPanel discreteStepPositionerPanel1;
    private javax.swing.JFormattedTextField jFormattedTextFieldEnd;
    private javax.swing.JFormattedTextField jFormattedTextFieldStart;
    private javax.swing.JFormattedTextField jFormattedTextFieldStepSize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
