package ch.psi.pshell.xscan.ui;

import ch.psi.pshell.xscan.model.PseudoPositioner;
import java.awt.Component;
import javax.swing.JFormattedTextField;

/**
 *
 */
public class PseudoPositionerPanel extends EditablePanel<PseudoPositioner> {

    public PseudoPositionerPanel() {
        this(new PseudoPositioner());
    }

    /**
     * Creates new form PseudoPositionerPanel
     */
    public PseudoPositionerPanel(final PseudoPositioner positioner) {
        super(positioner);
        if (positioner.getId() == null || positioner.getId().equals("")) {
            positioner.setId(IdGenerator.generateId());
        }

        initComponents();

        setManagedFields(jButton1,
                new Component[]{jFormattedTextFieldCount},
                new Component[]{jFormattedTextFieldSettlingTime, jTextFieldDone, jFormattedTextFieldDoneValue, jFormattedTextFieldDoneDelay, jComboBoxType},
                new String[]{"0.0", null, "1", "0.0", "Integer"}
        );

        // Establish bindings
        bindIdEditor(jTextFieldId);
        bindEditor(jFormattedTextFieldCount, "counts", true, 1);
        bindEditor(jFormattedTextFieldSettlingTime, "settlingTime", true, null);
        bindEditor(jTextFieldDone, "done", true);
        bindEditor(jFormattedTextFieldDoneValue, "doneValue", true, null);
        bindEditor(jFormattedTextFieldDoneDelay, "doneDelay", true, null);
        bindEditor(jComboBoxType, "type");

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jFormattedTextFieldCount = new JFormattedTextField(FieldUtilities.getIntegerFormat());
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextFieldSettlingTime = new JFormattedTextField(FieldUtilities.getDecimalFormat());
        jLabel4 = new javax.swing.JLabel();
        jTextFieldDone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jFormattedTextFieldDoneValue = new JFormattedTextField(FieldUtilities.getIntegerFormat());
        jLabel7 = new javax.swing.JLabel();
        jComboBoxType = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jFormattedTextFieldDoneDelay = new JFormattedTextField(FieldUtilities.getDecimalFormat());
        jButton1 = new javax.swing.JButton();

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setText("Id:");
        jPanel1.add(jLabel2);

        jTextFieldId.setBackground(getBackground());
        jTextFieldId.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jTextFieldId.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldId.setText("Id");
        jTextFieldId.setBorder(null);
        jTextFieldId.setInputVerifier(new IdInputVerifier());
        jTextFieldId.setPreferredSize(new java.awt.Dimension(80, 16));
        jPanel1.add(jTextFieldId);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setLabelFor(jFormattedTextFieldCount);
        jLabel1.setText("Count:");
        jPanel1.add(jLabel1);

        jFormattedTextFieldCount.setToolTipText("Number of pseudo steps");
        jFormattedTextFieldCount.setMinimumSize(new java.awt.Dimension(0, 0));
        jFormattedTextFieldCount.setPreferredSize(new java.awt.Dimension(80, 28));
        jPanel1.add(jFormattedTextFieldCount);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setLabelFor(jFormattedTextFieldSettlingTime);
        jLabel3.setText("Settling Time:");
        jPanel1.add(jLabel3);

        jFormattedTextFieldSettlingTime.setName("Settling Time"); // NOI18N
        jFormattedTextFieldSettlingTime.setPreferredSize(new java.awt.Dimension(80, 28));
        jPanel1.add(jFormattedTextFieldSettlingTime);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setLabelFor(jTextFieldDone);
        jLabel4.setText("Done:");
        jPanel1.add(jLabel4);

        jTextFieldDone.setName("Done"); // NOI18N
        jTextFieldDone.setPreferredSize(new java.awt.Dimension(180, 28));
        jPanel1.add(jTextFieldDone);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel5.setLabelFor(jFormattedTextFieldDoneValue);
        jLabel5.setText("Done Value:");
        jPanel1.add(jLabel5);

        jFormattedTextFieldDoneValue.setName("Done Value"); // NOI18N
        jFormattedTextFieldDoneValue.setPreferredSize(new java.awt.Dimension(80, 28));
        jPanel1.add(jFormattedTextFieldDoneValue);

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel7.setLabelFor(jComboBoxType);
        jLabel7.setText("Type:");
        jPanel1.add(jLabel7);

        jComboBoxType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Integer", "String", "Double" }));
        jComboBoxType.setName("Done Value Type"); // NOI18N
        jPanel1.add(jComboBoxType);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel6.setLabelFor(jFormattedTextFieldDoneDelay);
        jLabel6.setText("Done Delay:");
        jPanel1.add(jLabel6);

        jFormattedTextFieldDoneDelay.setName("Done Delay"); // NOI18N
        jFormattedTextFieldDoneDelay.setPreferredSize(new java.awt.Dimension(80, 28));
        jPanel1.add(jFormattedTextFieldDoneDelay);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ch/psi/pshell/xscan/ui/icons/plus.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jPanel1.add(jButton1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 938, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBoxType;
    private javax.swing.JFormattedTextField jFormattedTextFieldCount;
    private javax.swing.JFormattedTextField jFormattedTextFieldDoneDelay;
    private javax.swing.JFormattedTextField jFormattedTextFieldDoneValue;
    private javax.swing.JFormattedTextField jFormattedTextFieldSettlingTime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldDone;
    private javax.swing.JTextField jTextFieldId;
    // End of variables declaration//GEN-END:variables

}
