package ch.psi.pshell.xscan.ui;

import ch.psi.pshell.xscan.ProcessorXScan;
import ch.psi.pshell.xscan.model.Recipient;
import java.awt.Component;

/**
 *
 *
 */
public class RecipientPanel extends EditablePanel<Recipient> {

    public RecipientPanel() {
        this(new Recipient());
    }

    /**
     * Creates new form ShellAction
     */
    public RecipientPanel(Recipient recipient) {
        super(recipient);

        initComponents();

        setManagedFields(jButton1,
                new Component[]{jTextFieldSms},
                new Component[]{jCheckBoxError, jCheckBoxSuccess}
        );

        // Establish bindings
        bindEditor(jTextFieldSms, "value", true);
        bindEditor(jCheckBoxError, "error");
        bindEditor(jCheckBoxSuccess, "success");

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldSms = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jCheckBoxError = new javax.swing.JCheckBox();
        jCheckBoxSuccess = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();

        jTextFieldSms.setText("SMS, E-Mail");
        jTextFieldSms.setToolTipText("email address or SMS number");
        jTextFieldSms.setPreferredSize(new java.awt.Dimension(200, 28));

        jButton1.setText("Test");
        jButton1.setToolTipText("Send test notification");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCheckBoxError.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jCheckBoxError.setText("Error");
        jCheckBoxError.setName("Error"); // NOI18N

        jCheckBoxSuccess.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jCheckBoxSuccess.setText("Success");
        jCheckBoxSuccess.setName("Success"); // NOI18N

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ch/psi/pshell/xscan/ui/icons/plus.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTextFieldSms, javax.swing.GroupLayout.DEFAULT_SIZE, 803, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxSuccess)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jTextFieldSms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton1)
                .addComponent(jCheckBoxSuccess)
                .addComponent(jCheckBoxError)
                .addComponent(jButton2))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //ExecutionService service = Lookup.getDefault().lookup(ExecutionService.class);
        //service.testNotification(recipient.getValue());                
        ProcessorXScan cur = ProcessorXScan.getCurrent();
        if (cur != null) {
            cur.testNotification(getObject().getValue());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBoxError;
    private javax.swing.JCheckBox jCheckBoxSuccess;
    private javax.swing.JTextField jTextFieldSms;
    // End of variables declaration//GEN-END:variables

}
