package ch.psi.pshell.xscan.ui;

import ch.psi.pshell.xscan.model.Region;
import ch.psi.pshell.xscan.model.RegionPositioner;
import javax.swing.SwingUtilities;

/**
 *
 */
public class RegionPositionerPanel extends javax.swing.JPanel implements ObjectProvider<RegionPositioner> {

    private RegionPositioner positioner;

    public RegionPositionerPanel() {
        this(new RegionPositioner());
    }

    /**
     * Creates new form RegionPositionerPanel
     */
    public RegionPositionerPanel(RegionPositioner positioner) {

        if (positioner.getId() == null || positioner.getId().equals("")) {
            positioner.setId(IdGenerator.generateId());
        }
        this.positioner = positioner;

        initComponents();

        // Update view
        // -
        // Establish bindings
        // -
        collapsibleListContainer1.setHeader("Regions");
        collapsibleListContainer1.setName("Regions");
        collapsibleListContainer1.setIcon("list_num");

        SwingUtilities.invokeLater(() -> {
            //Must be executed later than  discreteStepPositionerPanel1.panelSupport.manage is called 
            discreteStepPositionerPanel1.getPanelSupport().addComponent(collapsibleListContainer1, new ComponentMetadata(false));
        });

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        discreteStepPositionerPanel1 = new DiscreteStepPositionerPanel(positioner);
        collapsibleListContainer1 = new CollapsibleListContainer<Region>(new RegionListItemProvider(positioner.getRegion()));

        discreteStepPositionerPanel1.setPreferredSize(new java.awt.Dimension(214, 32));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(discreteStepPositionerPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, Short.MAX_VALUE)
            .addComponent(collapsibleListContainer1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(discreteStepPositionerPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(collapsibleListContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ch.psi.pshell.xscan.ui.CollapsibleListContainer collapsibleListContainer1;
    private ch.psi.pshell.xscan.ui.DiscreteStepPositionerPanel discreteStepPositionerPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public RegionPositioner getObject() {
        return positioner;
    }

}
