package ch.psi.pshell.xscan.ui;

import ch.psi.pshell.xscan.model.ScalerChannel;
import java.awt.Component;
import java.util.HashMap;
import javax.swing.JFormattedTextField;

/**
 *
 */
public class ScalerChannelPanel extends EditablePanel<ScalerChannel> {

    public ScalerChannelPanel() {
        this(new ScalerChannel());
    }

    /**
     * Creates new form ScalerChannelPanel
     */
    public ScalerChannelPanel(final ScalerChannel detector) {
        super(detector);
        if (detector.getId() == null || detector.getId().equals("")) {
            detector.setId(IdGenerator.generateId());
        }

        initComponents();

        setManagedFields(null,
                new Component[]{jFormattedTextFieldNumber}
        );

        HashMap<Component, ComponentMetadata> managedFields = new HashMap<Component, ComponentMetadata>();
        managedFields.put(jFormattedTextFieldNumber, new ComponentMetadata(true));

        // Establish bindings
        bindIdEditor(jTextFieldId);
        bindEditor(jFormattedTextFieldNumber, "channel", false, 0);

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jFormattedTextFieldNumber = new JFormattedTextField(FieldUtilities.getIntegerFormat());

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setText("Id:");
        jPanel1.add(jLabel2);

        jTextFieldId.setBackground(getBackground());
        jTextFieldId.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jTextFieldId.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldId.setText("Id");
        jTextFieldId.setBorder(null);
        jTextFieldId.setInputVerifier(new IdInputVerifier());
        jTextFieldId.setPreferredSize(new java.awt.Dimension(80, 16));
        jPanel1.add(jTextFieldId);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setLabelFor(jFormattedTextFieldNumber);
        jLabel1.setText("Scaler Number:");
        jPanel1.add(jLabel1);

        jFormattedTextFieldNumber.setToolTipText("Number of the scaler");
        jFormattedTextFieldNumber.setPreferredSize(new java.awt.Dimension(40, 28));
        jPanel1.add(jFormattedTextFieldNumber);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField jFormattedTextFieldNumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldId;
    // End of variables declaration//GEN-END:variables

}
