package ch.psi.pshell.xscan.ui;

import ch.psi.pshell.xscan.model.Action;
import ch.psi.pshell.xscan.model.ContinuousDimension;
import ch.psi.pshell.xscan.model.DiscreteStepDimension;
import ch.psi.pshell.xscan.model.Manipulation;
import ch.psi.pshell.xscan.model.Scan;
import java.awt.Component;

/**
 *
 */
public class ScanPanel extends EditablePanel<Scan> {

    final Scan scan;

    public ScanPanel() {
        this(new Scan());
    }

    /**
     * Creates new form ScanPanel
     */
    public ScanPanel(Scan scan) {
        super(scan);
        this.scan = scan;

        initComponents();

        setManagedFields(jButton1,
                new Component[]{},
                new Component[]{collapsibleListContainerPre, collapsibleListContainerContinuousDimension, collapsibleListContainerDimension, collapsibleListContainerPost, collapsibleListContainerManipulation}
        );

        collapsibleListContainerPre.setHeader("Pre Actions");
        collapsibleListContainerPre.setName("Pre Actions");

        collapsibleListContainerContinuousDimension.setHeader("Continuous Dimension");
        collapsibleListContainerContinuousDimension.setName("Continuous Dimension");
        collapsibleListContainerContinuousDimension.setIcon("dimension");

        collapsibleListContainerDimension.setHeader("Dimensions");
        collapsibleListContainerDimension.setName("Dimensions");
        collapsibleListContainerDimension.setIcon("dimension");

        collapsibleListContainerPost.setHeader("Post Actions");
        collapsibleListContainerPost.setName("Post Actions");

        collapsibleListContainerManipulation.setHeader("Manipulations");
        collapsibleListContainerManipulation.setName("Manipulations");
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        collapsibleListContainerPre = new CollapsibleListContainer<Action>(new ActionListItemProvider(scan.getPreAction()));
        collapsibleListContainerDimension = new CollapsibleListContainer<DiscreteStepDimension>(new DiscreteStepDimensionListItemProvider(scan.getDimension()));
        collapsibleListContainerPost = new CollapsibleListContainer<Action>(new ActionListItemProvider(scan.getPostAction()));
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        collapsibleListContainerContinuousDimension = new CollapsibleListContainer<ContinuousDimension>(new ContinuousDimensionListItemProvider(scan));
        collapsibleListContainerManipulation = new CollapsibleListContainer<Manipulation>(new ManipulationListItemProvider(scan.getManipulation()));

        collapsibleListContainerPre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 51)));
        collapsibleListContainerPre.setName("Pre Actions"); // NOI18N

        collapsibleListContainerDimension.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 102)));
        collapsibleListContainerDimension.setToolTipText("Dimensions");
        collapsibleListContainerDimension.setName("Dimensions"); // NOI18N

        collapsibleListContainerPost.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 51)));
        collapsibleListContainerPost.setName("Post Actions"); // NOI18N

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ch/psi/pshell/xscan/ui/icons/plus.png"))); // NOI18N
        jButton1.setToolTipText("Add optional items");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jPanel1.add(jButton1);

        collapsibleListContainerContinuousDimension.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 0)));

        collapsibleListContainerManipulation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 153)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(collapsibleListContainerPre, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
            .addComponent(collapsibleListContainerContinuousDimension, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
            .addComponent(collapsibleListContainerDimension, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
            .addComponent(collapsibleListContainerPost, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
            .addComponent(collapsibleListContainerManipulation, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(collapsibleListContainerPre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(collapsibleListContainerContinuousDimension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(collapsibleListContainerDimension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(collapsibleListContainerPost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(collapsibleListContainerManipulation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ch.psi.pshell.xscan.ui.CollapsibleListContainer collapsibleListContainerContinuousDimension;
    private ch.psi.pshell.xscan.ui.CollapsibleListContainer collapsibleListContainerDimension;
    private ch.psi.pshell.xscan.ui.CollapsibleListContainer collapsibleListContainerManipulation;
    private ch.psi.pshell.xscan.ui.CollapsibleListContainer collapsibleListContainerPost;
    private ch.psi.pshell.xscan.ui.CollapsibleListContainer collapsibleListContainerPre;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
